### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by WinterWind33** [WinterWind33/fish-and-plants#114]
## Description

Update the README.md file in order to include a summary of the application, how to install it and credits.

## ToDos

- [x] Update the project description so that it better describes the overall project;
- [x] Add a credits section that contains third-party libraries;
- [x] Add an install section that includes information on how to compile the project;
